##### 1.Write a Python program to convert a list of numeric value into a one-dimensional NumPy array

In [2]:
import numpy as np

In [3]:
lst = [12.23, 13.32, 100,36.32]
arr = np.array(lst,dtype=float)
print(f" Original List : {lst}, Type : {type(lst)}")
print(f"One-dimensional numpy Array : {arr}, Type : {type(arr)}")


 Original List : [12.23, 13.32, 100, 36.32], Type : <class 'list'>
One-dimensional numpy Array : [ 12.23  13.32 100.    36.32], Type : <class 'numpy.ndarray'>


#####  2.Create a 3x3 matrix with values ranging from 2 to 10

In [4]:
array = np.arange(2,11).reshape(3,3)
print(array)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


##### 3.Write a Python program to create a null vector of size 10 and update sixth value to 11.
##### [ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
##### Update sixth value to 11
##### [ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [5]:
array = np.zeros(10)
print(array)
array[6] = 11
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


##### 4. Write a Python program to reverse an array (first element becomes last).
##### Original array: [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
##### Reverse array: [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [6]:
array = np.arange(12,38)
print(f"Original array: {array}")
array = array[::-1]
print(f"Reverse array: {array}")

Original array: [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array: [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


##### 5.Write a Python program to create a 2d array with 1 on the border and 0 inside.
##### Expected Output:
##### Original array:
[[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]]


[[ 1. 1. 1. 1. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 1. 1. 1. 1.]]

In [13]:
array = np.zeros((5,5))
print(array)
print("")
array[0,:] = array[1:-1,0] = array[-1,:] = array[1:-1,-1] = 1
print(array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


6. Write a Python program to add a border (filled with 0's) around an existing array.

In [14]:
array = np.ones((5,5))
print(array)
print("")
array[0,:] = array[1:-1,0] = array[-1,:] = array[1:-1,-1] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


7.Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:

In [17]:
# [[0 1 0 1 0 1 0 1]
# [1 0 1 0 1 0 1 0]
# [0 1 0 1 0 1 0 1]
# [1 0 1 0 1 0 1 0]
# [0 1 0 1 0 1 0 1]
# [1 0 1 0 1 0 1 0]
# [0 1 0 1 0 1 0 1]
# [1 0 1 0 1 0 1 0]]
array = np.zeros((8,8))
print(array)
print("")
array[::2,1::2] = array[1::2,::2] = 1
print(array)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


9. Write a Python program to append values to the end of an array.
Expected Output:
##### Original array:
- [10, 20, 30]
##### After append values to the end of the array:
- [10 20 30 40 50 60 70 80 90]

In [25]:
array = np.arange(10,40,10)
print(array)
arr2 = np.append(array,np.arange(40,100,10))
print(arr2)

[10 20 30]
[10 20 30 40 50 60 70 80 90]


11. Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements.
##### Expected Output:
- Size of the array: 3
- Length of one array element in bytes: 8
- Total bytes consumed by the elements of the array: 24

In [34]:
array = np.array([1,23,3])
print(f"Size of the array : {array.size}")
print(f"Length of the array element in bytes: {array.itemsize}")
print(f"Total bytes consumed by the elements of the array: {array.size * array.itemsize}")

Size of the array : 3
Length of the array element in bytes: 8
Total bytes consumed by the elements of the array: 24


12. Write a Python program to find common values between two arrays.
Expected Output:
Array1: [ 0 10 20 40 60]
Array2: [10, 30, 40]
Common values between two arrays:
[10 40]

In [36]:
arr1 = np.array([0,10,20,40])
arr2 = np.array([10,30,40])
print(f"Array1: {arr1}")
print(f"Array2: {arr2}")
print(f"Common values between two arrays: {np.intersect1d(arr1,arr2)}")

Array1: [ 0 10 20 40]
Array2: [10 30 40]
Common values between two arrays: [10 40]


13. Write a Python program to find the set difference of two arrays. The set difference
will return the sorted, unique values in array1 that are not in array2

In [ ]:
arr1 = np.array([0,10,20,40,60,80])
arr2 = np.array([10,30,40,50,70,90])
print(f"Array1: {arr1}")
print(f"Array2: {arr2}")
print(f"Unique values in array1 thta are not in array 2 : {np.setdiff1d(arr1,arr2)}")

Array1: [ 0 10 20 40 60 80]
Array2: [10 30 40 50 70 90]
Unique values in array1 thta are not in array 2 : [ 0 20 60 80]


14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or
will return the sorted, unique values that are in only one (not both) of the input arrays

In [39]:
arr1 = np.array([0,10,20,40,60,80])
arr2 = np.array([10,30,40,50,70])
print(f"Array1: {arr1}")
print(f"Array2: {arr2}")
print(f"Unique values that are in only one (not both) of the input arrays : {np.setxor1d(arr1,arr2)}")

Array1: [ 0 10 20 40 60 80]
Array2: [10 30 40 50 70]
Unique values that are in only one (not both) of the input arrays : [ 0 20 30 50 60 70 80]


15. Write a Python program compare two arrays using numpy.
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]

In [45]:
a = np.array([1,2])
b = np.array([4,5])
print(f"Array a : {a}")
print(f"Array b : {b}")
print(f"a>b \n{a>b}")
print(f"a>=b \n{a>=b}")
print(f"a<b \n{a<b}")
print(f"a<=b \n{a<=b}")

Array a : [1 2]
Array b : [4 5]
a>b 
[False False]
a>=b 
[False False]
a<b 
[ True  True]
a<=b 
[ True  True]


15. Write a Python program to save a NumPy array to a text file.

In [47]:
a = np.array([1,2,3,5,89])
path = 'D:/BridgeLabz_Di/python_programs/BL-Numpy/15_numpy.txt'
np.savetxt(path,a,delimiter=',', fmt='%.2f')

16. Write a Python program to create a contiguous flattened array.
Original array:
[[10 20 30]
[20 40 50]]

In [73]:
array = np.array([[10,20,30],[20,40,50]])
print(f"Original array : \n{type(array)}")
print(array.flatten())


Original array : 
<class 'numpy.ndarray'>
[10 20 30 20 40 50]


17. Write a Python program to change the data type of an array.
Expected Output:
[[ 2 4 6]
[ 6 8 10]]
Data type of the array x is: int32
New Type: float64
[[ 2. 4. 6.]
[ 6. 8. 10.]]

In [78]:
x = np.array([[10,20,30],[20,40,50]], dtype=np.int32)
print(f"Origina Array: \n{x}")
print(f"Data type of the array x is: {x.dtype}")
x =x.astype(np.float64)
print(f"New Type: {x.dtype} \n{x}")

Origina Array: 
[[10 20 30]
 [20 40 50]]
Data type of the array x is: int32
New Type: float64 
[[10. 20. 30.]
 [20. 40. 50.]]


18. Write a Python program to create a 3-D array with ones on a diagonal and zeros
elsewhere.
Expected Output:
[[ 1. 0. 0.]
[ 0. 1. 0.]
[ 0. 0. 1.]]

In [84]:
array = np.zeros((3,3))
print(array)
print("")
for i in range((len(array))):
    array[i,i] = 1
print(array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


19. Write a Python program to create an array which looks like below array.
Expected Output:

In [92]:
array = np.zeros((4,3))
print(array)
print("")
for i in range(1,len(array)):
        array[i,:i] = 1
print(array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


20. Write a Python program to concatenate two 2-dimensional arrays.
Expected Output:

In [ ]:
arr1 = np.array([[0, 1, 3], [5, 7, 9]])
arr2 = np.array([[0, 2, 4], [6, 8, 10]])
print(arr1,arr2)
arr1 = np.concatenate((arr1,arr2),axis=1)
print(arr1)

[[0 1 3]
 [5 7 9]] [[ 0  2  4]
 [ 6  8 10]]
[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


21. Write a Python program to make an array immutable (read-only).
Expected Output:

In [106]:
array = np.zeros(7)
print(array)
array[2]=7
print(array)
array.setflags(write=False)
array[3] = 5

[0. 0. 0. 0. 0. 0. 0.]
[0. 0. 7. 0. 0. 0. 0.]


ValueError: assignment destination is read-only

22. Write a Python program to create an array of (3, 4) shape, multiply every element
value by 3 and display the new array

In [109]:
array = np.arange(12).reshape(3,4)
print(f"Original Array Elements :\n{array}")
array = array[:] * 3
print(f"New Array Elements :\n{array}")


Original Array Elements :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
New Array Elements :
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


23. Write a Python program to convert a NumPy array into Python list structure.
Expected Output:

In [114]:
arr = np.arange(6).reshape(3,2)
print(arr)
arr_list = arr.tolist()
print(arr_list)

[[0 1]
 [2 3]
 [4 5]]
[[0, 1], [2, 3], [4, 5]]


24. Write a Python program to convert a NumPy array into Python list structure

In [123]:
arr = np.array([0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349,0.35399976, 0.99469633, 0.0694458, 0.54711478])
arr= np.round(arr,decimals=3)
arr_list = arr.tolist()
print(f"{arr_list}")

[0.262, 0.528, 0.572, 0.593, 0.783, 0.697, 0.354, 0.995, 0.069, 0.547]


25. Write a Python program to suppresses the use of scientific notation for small
numbers in numpy array.

In [136]:
np.set_printoptions(suppress=False)
array = np.array([1.60000000e-10,1.60000000e+00,1.20000000e+03,2.35000000e-01])
print(f"Original Array Elements : {array}")
np.set_printoptions(suppress=True,precision=3)
print(f"Print array values with precision 3: \n{array}")

Original Array Elements : [1.60e-10 1.60e+00 1.20e+03 2.35e-01]
Print array values with precision 3: 
[   0.       1.6   1200.       0.235]


26. Write a Python program to how to add an extra column to an numpy array.

In [144]:
arr = np.array([[10,20,30,100]])
print(arr)
print("")
arr = np.concatenate((arr,[[40,50,60,200]]),axis=0)
print(arr)

[[ 10  20  30 100]]

[[ 10  20  30 100]
 [ 40  50  60 200]]


27. Write a Python program to remove specific elements in a numpy array.

In [146]:
array = np.arange(10,110,10)
print(f"Original Array : \n{array}")
array = np.delete(array,[0,3,4])
print(f"Delete first, fourth and fifth elements:\n{array}")

Original Array : 
[ 10  20  30  40  50  60  70  80  90 100]
Delete first, fourth and fifth elements:
[ 20  30  60  70  80  90 100]
